# Generated by Django 5.1.5 on 2025-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                ("name", models.CharField(max_length=155, verbose_name="Имя")),
                (
                    "image",
                    models.ImageField(upload_to="settings/", verbose_name="Фото"),
                ),
                (
                    "image2",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 2"),
                ),
                ("job", models.CharField(max_length=155, verbose_name="Где работает")),
            ],
            options={
                "verbose_name": "Настройка",
                "verbose_name_plural": "Настройки",
            },
        ),
    ]
