# Generated by Django 5.1.5 on 2025-01-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                (
                    "title2",
                    models.CharField(max_length=155, verbose_name="Заголовок 2"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name_plural": "О нас",
            },
        ),
    ]
