# Generated by Django 5.1.5 on 2025-01-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_end_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='End_Work',
            new_name='Work',
        ),
    ]
