# Generated by Django 5.1.5 on 2025-01-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_rename_end_work_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='End_Work',
        ),
    ]
