# Generated by Django 5.1.5 on 2025-01-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_rename_work_end_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=155, verbose_name='ключ')),
                ('value', models.CharField(max_length=155, verbose_name='Значение')),
            ],
            options={
                'verbose_name_plural': 'Веб дизайн',
            },
        ),
    ]
