# Generated by Django 5.1.5 on 2025-01-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(default=1, upload_to='info', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
