# Generated by Django 5.1.5 on 2025-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_design_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=155, verbose_name='ключ')),
                ('value', models.CharField(max_length=155, verbose_name='Значение')),
                ('image', models.ImageField(upload_to='info', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Разработка',
            },
        ),
    ]
