# Generated by Django 5.1.5 on 2025-01-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_photography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun_facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('title2', models.CharField(max_length=155, verbose_name='Заголовок 2')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Интересные факты',
            },
        ),
    ]
