# Generated by Django 5.1.5 on 2025-01-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_custom_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_cms',
            name='value2',
            field=models.TextField(default=1, max_length=155, verbose_name='Значение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custom_cms',
            name='value3',
            field=models.TextField(default=11, max_length=155, verbose_name='Значение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custom_cms',
            name='value',
            field=models.TextField(max_length=155, verbose_name='Значение'),
        ),
    ]
