# Generated by Django 5.1.5 on 2025-01-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_custom_cms_value2_custom_cms_value3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_CMS2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=155, verbose_name='ключ')),
                ('value', models.TextField(max_length=155, verbose_name='Значение')),
                ('value2', models.TextField(max_length=155, verbose_name='Значение')),
                ('value3', models.TextField(max_length=155, verbose_name='Значение')),
                ('image', models.ImageField(upload_to='info', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Пользовательская CMS',
            },
        ),
        migrations.CreateModel(
            name='Custom_CMS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=155, verbose_name='ключ')),
                ('value', models.TextField(max_length=155, verbose_name='Значение')),
                ('value2', models.TextField(max_length=155, verbose_name='Значение')),
                ('value3', models.TextField(max_length=155, verbose_name='Значение')),
                ('image', models.ImageField(upload_to='info', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Пользовательская CMS',
            },
        ),
        migrations.CreateModel(
            name='Custom_CMS4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=155, verbose_name='ключ')),
                ('value', models.TextField(max_length=155, verbose_name='Значение')),
                ('value2', models.TextField(max_length=155, verbose_name='Значение')),
                ('value3', models.TextField(max_length=155, verbose_name='Значение')),
                ('image', models.ImageField(upload_to='info', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Пользовательская CMS',
            },
        ),
    ]
